### PR TITLE
Changed the labels and placeholder

### LINKED ISSUE #170: [Enhancement]: Improve label of the input elements on the landing page
## Label not explanatory enough in the current game landing page
The current game has each label as the expected number of values per inputs. This should also indicate which of the input is column or row or number of players

<br/>
<br/>

image

### Describe the solution you'd like

I'd like a some enhancement to be made to the label of each input to increase UC. 

- [ ] `Row input`. Label should be `No of Rows` and the placeholder for the input should be `"Enter no of rows"`
- [ ] `Column input`, Label should be `No of Columnss` and the placeholder for the input should be `"Enter no of columns"`
- [ ] `Players Input` Label should be `No of Playerss` and the placeholder for the input should be `"Enter no of players"`

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by sdas1311**
## PR Description 📜

Fixes #170

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have changed Row input. Label to No of Rows and the placeholder for the input should be "Enter no of rows".
- [x] I have changed Column input, Label to No of Columns and the placeholder for the input should be "Enter no of columns".
- [x] I have changed Players Input Label to No of Players and the placeholder for the input should be "Enter no of players"
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-17 232802

--- 
<br>

### CODE REVIEW

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
The Label Text color should be the same color and font size of the span element that says `(between 5 and 30)`
Also the placeholder should only show id there is no default value in the input element. 

When the game is started, there is a default value in each input, that should not be changed, only if the inputs are empty that's when the placeholder should show and also you need to add a CSS styling to the placeholder

**Comment by Lovelyfin00** [comment]
Also, I just found out that there was already labels in each input before. You can revert the labels to the previous ones but change the color so that it can become more noticable

**Comment by sdas1311** [comment]
> The Label Text color should be the same color and font size of the span element that says `(between 5 and 30)` Also the placeholder should only show id there is no default value in the input element.

**Comment by sdas1311** [comment]
Yes I understood and changed it, but can you clarify that do I have to change the font size of span element that says (between 5 and 30)?

**Comment by sdas1311** [comment]
Yes, I made the labels more noticable and reverted the labels to the previous ones.
Also only if the inputs are empty that's when the placeholder shown and added a CSS styling to the placeholder font.
Is there any other changes required?

**Comment by Lovelyfin00** [comment]
> Yes, I made the labels more noticable and reverted the labels to the previous ones.
> Also only if the inputs are empty that's when the placeholder shown and added a CSS styling to the placeholder font.
> Is there any other changes required?

Can you include a screenshot. I’ll do a proper review soon

**Comment by sdas1311** [comment]
> > Yes, I made the labels more noticable and reverted the labels to the previous ones.
> > Also only if the inputs are empty that's when the placeholder shown and added a CSS styling to the placeholder font.
> > Is there any other changes required?
> 
> Can you include a screenshot. I’ll do a proper review soon

# When the game is started, there is a default value in each input

Screenshot 2024-05-18 223011

# When the inputs are empty that's when the placeholder is shown 

Screenshot 2024-05-18 223042

**Comment by sdas1311** [comment]
> > It's already being 2 days please review it soon

**Comment by sdas1311** [comment]
> > Yes, I made the labels more noticable and reverted the labels to the previous ones.
> > Also only if the inputs are empty that's when the placeholder shown and added a CSS styling to the placeholder font.
> > Is there any other changes required?
> 
> Can you include a screenshot. I’ll do a proper review soon

It's already being 2 days please review it soon...

**Comment by Lovelyfin00** [comment]
This is perfect
I’ll review it today
Will drop comments if it’s needed

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
in the style.css file from line 348 to 350, there's no closing curly braces @sdas1311 
Also add `font-size: 16px` to the placeholder style

**Review by Lovelyfin00 — APPROVED** [review]
LGTM
NIce work @sdas1311

**Comment by sdas1311** [comment]
Why the changes are not reflecting in the webpage? @Lovelyfin00

**Pull request merged**
