### PR TITLE
Add Mute Button Functionality

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
## PR Description 📜

This pull request addresses issue #17. I have implemented the mute button functionality as per the requirements outlined in the issue. Users can now easily mute audio within the application with the click of a button, enhancing their control over their audio experience. I have followed the project's contributing guidelines and performed a self-review of the code to ensure its quality. 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
1. there are 2 conflicts in the index.html and style.css, please review them once more 
2. use the PR template properly with the tick marks.

**Comment by thevijayshankersharma** [comment]
@ayush-t02 Conflict has been solved

**Comment by ayush-t02** [comment]
good work, what about the tick marks in the PR?

**Comment by thevijayshankersharma** [comment]
Done

**Comment by thevijayshankersharma** [comment]
@ayush-t02 you didn't assign any level label.

**Pull request merged**
