### PR TITLE
[New Feature]: Add Theme Switcher Button to Change Background Video

### LINKED ISSUE #160: [New Feature]: Add Theme Switcher Button to Change Background Video
### 🎮 feature Request

The feature adds a theme switcher button to the website, allowing users to choose between different background videos. When the user clicks the theme switcher button, a dropdown with theme options appears. Selecting a theme changes the background video to the corresponding choice. 

This feature will add more background theme for the user such as waterfall, nature, etc. This will help in improving user experience by providing the user options for customizing the background of the website. 

I will add a background folder to the project directory, which will contain all the background videos. This folder will be referenced in the code to dynamically switch between different video backgrounds based on the selected theme.

### Point down the features

 Theme Switcher Button: A button labeled "Change Theme" to allow users to access different background themes.
 Theme Options Dropdown: A dropdown menu with multiple theme options that change the background video when selected.
 Background Video Switching: Different background videos are loaded and played based on the selected theme.
 Overlay Container: An overlay container with a semi-transparent background to ensure content visibility over the background videos.
Enhanced Readability: Improved text color and visibility for better contrast and readability against varying background videos.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

introduces a theme switcher feature that allows users to choose from multiple background themes via a dropdown menu.
Changes include the addition of a theme-button to open the dropdown menu for theme selection, updates to the HTML structure to support the new themes, and CSS adjustments to ensure content visibility over the video backgrounds. The JavaScript code in the new theme.js file manages the theme switching logic and persistence. The background videos are stored in a new background folder for easy management.
Additionally, a background video will keep playing during the duration of the game. 
Fixes #160 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

image

image

image

--- 
<br>
<hr>

## Video demo

https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/92214013/15736684-52bd-4965-8801-81c2b97d858d

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
Nice job you've got here. 
Just a quick fix needed.  When a theme is selected, you need to change the style of the particular theme option to show that it's selected. Like I select `Aurora` theme style and then I close the theme options, when I click that option again and want to select another style, it should show that `Aurora` is what is currently selected.

Also when I select an other, the theme dropdown should close or if possible you can close the theme dropdown when I click anywhere outside the theme container

**Comment by aditya-bhaumik** [comment]
https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/92214013/f02777fd-022a-4eec-a7c0-a5964af7984a

 @Lovelyfin00  I have fixed the code so that the change theme dropdown closes when a theme is selected, and the selected theme's style changes to indicate to the user which theme has been selected.

**Comment by Lovelyfin00** [comment]
Hi @ayush-t02 
Can you create a pr merging these changes to develop branch?
All PR created during gssoc should be merged to develop

**Comment by ayush-t02** [comment]
@Lovelyfin00 sure

**Pull request merged**
