### PR TITLE
Validate rows, columns and players

### LINKED ISSUE #143: [Bug]:
### Give a brief about the bug ✍️

When attempting to set the number of rows, columns, and players on the homepage, inputs outside the acceptable range are currently being accepted. 
image

### What is the expected behavior? 🤔

Users should receive a validation message when attempting to input values for rows, columns, and number of players outside the acceptable range. This message should prompt them to provide values within the specified range.

### Provide step by step information reproduce the bug 📄

1. Open the application and navigate to the homepage.
2. Locate the input fields for setting the number of rows, columns, and players.
3. Input values for rows, columns, and players that are outside the specified acceptable range.
4. Submit the input by clicking the appropriate button or triggering the submission action.
5. Observe the application's response. Note that there is no validation message displayed despite the inputs being outside the acceptable range.
6. Verify that the submitted values are accepted by the application without any indication of error or constraint violation.
7. Attempt to proceed with the application flow or perform actions dependent on these inputs to observe any unexpected behavior or errors that may occur as a result.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by adityakishore25**
## PR Description 📜

Fixes #143

Fix: Implemented input validation for rows, columns, and number of players to ensure they fall within the specified ranges. Users will now receive clear and specific validation messages prompting them to provide values within the acceptable range before starting the game.
<hr>
 
## Mark the task you have completed ✅

- ✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- ✅ I have performed a self-review of my own code or work.
- ✅ I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅ I have added screenshot for review.

## Validation of number rows:
Screenshot from 2024-05-17 20-52-38
## Validation of number columns:
image
## Validation of number of palyers:
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Lovelyfin00 — APPROVED** [review]
LGTM

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
Hi @adityakishore25 
Nice work you've got here
Just a quick question
Is there a reason why the `style="color: rgb(52, 76, 100);"` was removed from the label element?

**Comment by adityakishore25** [comment]
> Hi @adityakishore25 Nice work you've got here Just a quick question Is there a reason why the `style="color: rgb(52, 76, 100);"` was removed from the label element?

That was a mistake. I have pushed my files again, and now everything is fine. Please review the updated changes.

Thank you!

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
You aren't supposed to remove the style from the start button

```
 style="background-color:rgb(87, 123, 141);"
```

**Comment by adityakishore25** [comment]
Updated style in start button.

**Comment by Lovelyfin00** [comment]
Can you resolve the merge conflicts? Do you know how to do that? @adityakishore25

**Comment by adityakishore25** [comment]
@Lovelyfin00 done from my side. I've checked the code.

image
But these buttons are not working or I think they are not implemented yet. Mute button is working fine.

**Comment by Lovelyfin00** [comment]
Hey @adityakishore25 
Your PR looks like it broke some things.
This is how `develop` branch looks like to me below
<br/>
<br/>
image
<br/>
<br/>

This is how your branch looks like to me below
<br/>
<br/>
image

**Comment by Lovelyfin00** [comment]
What you can do is close this your PR, update your copy of develop and create a new branch from it and start working on the PR from scratch

**Comment by adityakishore25** [comment]
Okay, fine

**Pull request closed without merging**
